# Generated by Django 3.2.9 on 2021-11-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
